-- MySQL Script generated by MySQL Workbench
-- Sun Sep 14 20:06:39 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zend-rest-api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zend-rest-api` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `zend-rest-api` ;

-- -----------------------------------------------------
-- Table `zend-rest-api`.`brewery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zend-rest-api`.`brewery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zend-rest-api`.`beer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zend-rest-api`.`beer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brewery_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `style` VARCHAR(45) NULL,
  `ibu` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `brewery_id_idx` (`brewery_id` ASC),
  CONSTRAINT `brewery_id`
    FOREIGN KEY (`brewery_id`)
    REFERENCES `zend-rest-api`.`brewery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
